version : "3"


services:
#   analyser_app:
#     build:
#       context: .
#       dockerfile: Dockerfile

#       volumes:
#       - ./docker_resource/pg_data:/var/lib/postgresql/data
#       - ./Data_files/feature_data/target_data:/opt/source_data
#       depends on:
#         - postgres
#         - pgadmin
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 10s
    timeout: 5s
    retries: 5
    depends_on:
      postges:
        condition: service_healthy
  postges:
    image: "postgres:13.8"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${pg_password}
      - POSTGRES_USER=${pg_user}
      - POSTGRES_DB=${pg_database}
    volumes:
      - /docker_resource/pg_data:/var/lib/postgresql/data
      - /Data_files/feature_data/target_data:/opt/source_data
    
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "80:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=sharmarituparna66@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Ritu@@13579
