version : "3"


services:
#   analyser_app:
#     build:
#       context: .
#       dockerfile: Dockerfile

#       volumes:
#       - ./docker_resource/pg_data:/var/lib/postgresql/data
#       - ./Data_files/feature_data/target_data:/opt/source_data
#       depends on:
#         - postgres
#         - pgadmin
  postges:
    image: "postgres:13.8"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${pg_password}
      - POSTGRES_USER=${pg_user}
      - POSTGRES_DB=${pg_database}
    volumes:
      - /docker_resource/pg_data:/var/lib/postgresql/data
      - /Data_files/feature_data/target_data:/opt/source_data
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "80:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=sharmarituparna66@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Ritu@@13579
