# preprocess path
destination:
  clean_data_source_csv : ..\clean_data

  # excel and data files

get_utility : 
  data_path : ..\data\*
  clean_data_path : ..\clean_data\*.csv
  feature_data_path : ..\feature_data
