name: python-app-build

on: 
  push:
    branch: main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  build:

    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup upterm session
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name : install requirements
      run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    - name : setup python path
      run: export PYTHONPATH=$PYTHONPATH:/src

    - name: run docker compose file
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "database.yml"

