name: python-app-build

on: 
  push:
    branches: main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: x64
    - name : setup python path
      run: |
          export PYTHONPATH=$PYTHONPATH:/src
          sudo PATH=$PATH:/usr/pgsql-9.3/bin/ pip install psycopg2
    
    - name : install requirements
      run: |
            sudo apt update && sudo apt upgrade -y
            pip install --upgrade setuptools
            python -m pip install --upgrade pip
            pip install -r requirements.txt

    - name: run docker compose file
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "database.yml"

    - name: get container name
      run: docker ps
    
    - name: get ip address
      run: docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
      
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3


