name: name of the file

on: 
  push:
    branch: main

jobs:
  build:

    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
       python-version: '3.8'

    - name : install requirements
      run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    - name : setup python path
      run: export PYTHONPATH=$PYTHONPATH:/src

    - name: run docker compose file
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "database.yml"

